### PR TITLE
Added Visor Finance.

### PR DESCRIPTION
**Pull request by loogle18**
CryptoFees info (1)

### CODE REVIEW

**Comment by loogle18** [comment]
Added [Visor Finance](https://www.coingecko.com/en/coins/visor), @dmihal please take a look.
[Token Terminal](https://www.tokenterminal.com/terminal/projects/visor-finance) for reference.

**Comment by dmihal** [comment]
Hmm it doesn't seem to be working correctly... there's no data on https://crypto-fees-git-fork-loogle18-visor-crypto-fees-info.vercel.app/protocol/visor, and it doesn't show up on the main list either

**Comment by dmihal** [comment]
I deployed the most recent commit, deployed here:

https://crypto-fees-bz15fj0gr-crypto-fees-info.vercel.app/protocol/visor

Still doesn't seem to be getting the data correctly. When I get a chance, I'll try to run it locally and see what the issue is

**Comment by loogle18** [comment]
Hey sorry @dmihal I was off for quite some time. Decided to revisit this PR and it seems that I found the issue.
There was something with datetime conversion. Seems like for a local env my method worked, but not for remote env.
I just rewrote the adapter to use your `dateToTimestamp` from `/lib/time` and data started to be shown on vercel app.

Here's data page:
Screenshot 2021-11-03 at 21 15 27


Here's app: https://crypto-fees-git-visor-loogle18.vercel.app/protocol/visor

**Pull request merged**
