### PR TITLE
Hegic added to CryptoFees

### PR DESCRIPTION
**Pull request by remote-gildor**
@dmihal Hi, I've added Hegic to CryptoFees. Hegic is the biggest DeFi options/hedging protocol. 🙂 

Every time a user creates a new option, a (protocol) fee is deduced. That's why the graph query that I made searches for new options created (based on the timestamp) within the last 24h, and also within the last 7 days.

```graphql
yesterday: options(first: 1000, where: {timestamp_gt: ${yesterdayTimestamp}}) {
  settlementFee
  symbol
}
weekAgo: options(first: 1000, where: {timestamp_gt: ${sevenDaysTimestamp}}) {
  settlementFee
  symbol
}
```

There are two types of Hegic options: ETH options and WBTC options. Fees are thus paid in either ETH or WBTC (depends on the type of an option).

That's why I also needed to fetch ETH and WBTC prices from CoinGecko in order to calculate total fees:

```javascript
// get ETH and BTC prices from CoinGecko
const priceCache: { [symbol: string]: number } = { usd: 1 };

const getPrice = async (name: string): Promise<number> => {
  if (!priceCache[name]) {
    const request = await fetch(
      `https://api.coingecko.com/api/v3/simple/price?ids=${name}&vs_currencies=usd`
    );
    const response = await request.json();
    priceCache[name] = response[name].usd;
  }

  return priceCache[name];
};

const ethPrice = await getPrice("ethereum");
const wbtcPrice = await getPrice("wrapped-bitcoin");

// calculate total fees in USD over the past 24h hours
const totalFeesYesterday = (ethFeesYesterday * ethPrice) + (wbtcFeesYesterday * wbtcPrice);
const totalFeesWeek = (ethFeesWeek * ethPrice) + (wbtcFeesWeek * wbtcPrice);
```

If you have any questions, I'm happy to answer 🙂

### CODE REVIEW

**Comment by remote-gildor** [comment]
@dmihal Do you have to merge it manually, or is it done automatically?

**Comment by dmihal** [comment]
Hey @remote-gildor, thanks for the contribution!

One thing I noticed is that your code fetches fees from the previous 24 hours, while other fees on the site come from 1 UTC day period.

Do you think you can update your query to get the previous UTC day?

Also, you're fetching the _current_ BTC & ETH price and multiplying that over fees taken over the past week. This is _probably_ pretty negligible, but in the future it would be nice to query historical price data to make the data slightly more accurate.

Do you mind leaving a comment in your code about this so it can possibly get fixed in the future?

**Comment by remote-gildor** [comment]
@dmihal okay, on it! 🙂

**Comment by remote-gildor** [comment]
Done! Now getting data for the previous full UTC day instead of the past 24 hours (similarly for the previous 7 days). 🙂

**Pull request merged**
